### ISSUE TITLE
vfio-ioctls: LittleEndian in enable_irq()

### ISSUE THREAD

**Issue by juru1234** [rust-vmm/vfio#38]
Hi,

I'm using the `vfio-ioctls` crate on a big endian machine and `enable_irq()` doesn't work because it uses `LittleEndian::write_u32(fd, event_fd.as_raw_fd() as u32);`. Why is this explicit `LittleEndian::write_u32` used? Can we change it to a normal write?

**Comment by juru1234** [comment]
Maybe we can just change this to `NativeEndian` instead of `LittleEndian`?

**Comment by juru1234** [comment]
@epilys @jiangliu We would really love to use this crate on IBM Z which runs big endian Linux. Are there any active mailing list where I can send a patch?

**Comment by epilys** [comment]
@juru1234 I'm not sure about this, but it might have been used because the kernel used to assume LE until 2018 (? `07fd7ef3a1c25a11015bb5821c9c5982f722d4a2`). We accept PRs.

**Comment by juru1234** [comment]
See #53
